resources:
  - ./db/postres-deployment.yaml
  - ./db/postres-pvc.yaml
  - ./db/postres-svc.yaml


configMapGenerator:
  - name: fastapi-config
    envs:
      - fastapi/fastapi.env
  - name: vue-config
    envs:
      - vue/vue.env

generatorOptions:
  disableNameSuffixHash: true
