resources:
  - ./db/postgres-deployment.yaml
  - ./db/postgres-pvc.yaml
  - ./db/postgres-svc.yaml
  - ./fastapi/fastapi-deployment.yaml
  - ./fastapi/fastapi-svc.yaml
  - ./vue/vue-deployment.yaml
  - ./vue/vue-svc.yaml
  - ./vue/vue-ingress.yaml



configMapGenerator:
  - name: fastapi-config
    envs:
      - fastapi/fastapi.env
  - name: vue-config
    envs:
      - vue/vue.env

generatorOptions:
  disableNameSuffixHash: true
