app:
  env:
    DATABASE_URL: 'postgres://appuser:apppassword@dbserver:5432/appdb'
    

vueapp:
  VUE_APP_API_URL:  http://192.168.56.103
backend_server_url: "http://192.168.56.101:8000"

service:
  workingdir: "{{app_dir}}"
  execstart: "{{app_dir}}/favenv/bin/uvicorn src.main:app --host 0.0.0.0 --port 8000"