app:
  env:
    DATABASE_URL: 'postgres://appuser:apppassword@dbserver:5432/appdb'

service:
  workingdir: "{{app_dir}}"
  execstart: "{{app_dir}}/favenv/bin/uvicorn src.main:app --host 0.0.0.0 --port 8000"