apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: vue
  template:
    metadata:
      labels:
        component: vue
    spec:
      containers:
        - name: vue
          image: 'tsadimas/vue-cp:0.1'
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: vue-config
          imagePullPolicy: Always
