apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fastapi
  template:
    metadata:
      labels:
        component: fastapi
    spec:
      serviceAccountName: pull-sa
      containers:
        - name: fastapi
          image: ghcr.io/tsadimas/cp-backend:42b15bf-24
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: fastapi-config
          imagePullPolicy: Always
