---
- hosts: appservers

  vars:
    user_dir: "{{ ansible_env.HOME }}"
    app_dir: "{{user_dir}}/fastapi"
    git_repo_url: "git@github.com:tsadimasteaching/cloud-platforms-fastapi-vue.git"
    git_repo_branch: "main"
    app_port: 8000


  tasks:

    - name: ensure github.com is a known host
      lineinfile:
        dest: "{{user_dir}}/.ssh/known_hosts"
        create: yes
        state: present
        line: "{{lookup('pipe', 'ssh-keyscan -t rsa github.com')}}"
        regexp: "^github\\.com"


    - name: Clone repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ansible_env.HOME}}/project"
        version: "{{ git_repo_branch}}"
        force: yes
